version: "2.0"

services:
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    networks:
      - kafkanet
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092

  articleprocessor:
    image: articleprocessor
    container_name: articleprocessor
    networks:
      - kafkanet
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafkaserver:9092
      DATABASE_HOST: database # 172.17.0.2
      DATABASE_PORT: 5432
    depends_on:
       - kafkaserver
       - database
    ports:
      - 2000:2000
    links:
      - kafkaserver:kafkaserver

  stockprocessor:
    image: stockprocessor
    container_name: stockprocessor
    networks:
      - kafkanet
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafkaserver:9092
      DATABASE_HOST: database # 172.17.0.2
      DATABASE_PORT: 5432
    depends_on:
       - kafkaserver
       - database
    ports:
      - 2001:2001
    links:
      - kafkaserver:kafkaserver
      - stockscraper:stockscraper
        
  database:
    image: database
    container_name: database
    hostname: database
    networks:
      - kafkanet
    environment:
      POSTGRES_DB: scraper
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: password
    ports:
      - "5445:5432"
    depends_on:
      - kafkaserver
    volumes:
      - my-vol:/var/lib/postgresql/data
    restart: unless-stopped

  singlescraper:
    image: singlescraper
    container_name: singlescraper
    networks:
      - kafkanet
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafkaserver:9092
    depends_on:
       - kafkaserver
       - database
    ports:
      - 2003:2003
    links:
      - kafkaserver:kafkaserver

  stockscraper:
    image: stockscraper
    container_name: stockscraper
    networks:
      - kafkanet
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafkaserver:9092
    depends_on:
       - kafkaserver
       - database
    ports:
      - 3000:3000
    environment:
      ADVERTISED_HOST: stockscraper
      ADVERTISED_PORT: 3000

networks:
  kafkanet:
    driver: bridge

volumes:
  my-vol:
