version: "2.1"

services:
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    networks:
      - kafkanet
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092

  articleprocessor:
    image: articleprocessor
    container_name: articleprocessor
    networks:
      - kafkanet
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafkaserver:9092
    depends_on:
       - kafkaserver
    ports:
      - 2000:2000
    links:
      - kafkaserver:kafkaserver
      
networks:
  kafkanet:
    driver: bridge